// Detailed business type mapping for each symbol
// Serves as immediate fallback before async Yahoo sector lookup completes
// Based on actual Yahoo Finance industry classifications
export const INDUSTRY_MAP: Record<string, string> = {
  // Technology - Software
  MSFT: "Software - Infrastructure",
  ADBE: "Software - Application",
  CRM: "Software - Application",
  NOW: "Software - Application",
  INTU: "Software - Application",
  ADSK: "Software - Application",
  SNPS: "Software - Application",
  CDNS: "Software - Application",
  ANSS: "Software - Application",
  TYL: "Software - Application",
  PTC: "Software - Application",
  CTSH: "Information Technology Services",
  ACN: "Information Technology Services",
  IT: "Information Technology Services",
  EPAM: "Information Technology Services",
  ORCL: "Software - Infrastructure",
  PANW: "Software - Infrastructure",
  FTNT: "Software - Infrastructure",
  GEN: "Software - Infrastructure",
  AKAM: "Software - Infrastructure",
  // Technology - Hardware & Semiconductors
  AAPL: "Consumer Electronics",
  NVDA: "Semiconductors",
  AVGO: "Semiconductors",
  INTC: "Semiconductors",
  TXN: "Semiconductors",
  QCOM: "Semiconductors",
  AMD: "Semiconductors",
  AMAT: "Semiconductor Equipment & Materials",
  ADI: "Semiconductors",
  LRCX: "Semiconductor Equipment & Materials",
  MU: "Semiconductors",
  KLAC: "Semiconductor Equipment & Materials",
  MCHP: "Semiconductors",
  ON: "Semiconductors",
  NXPI: "Semiconductors",
  SWKS: "Semiconductors",
  MPWR: "Semiconductors",
  TER: "Semiconductor Equipment & Materials",
  KEYS: "Scientific & Technical Instruments",
  ZBRA: "Scientific & Technical Instruments",
  TRMB: "Scientific & Technical Instruments",
  // Technology - Internet & Services
  GOOGL: "Internet Content & Information",
  GOOG: "Internet Content & Information",
  META: "Internet Content & Information",
  CSCO: "Communication Equipment",
  JNPR: "Communication Equipment",
  FFIV: "Communication Equipment",
  // Healthcare - Pharma
  JNJ: "Drug Manufacturers - Diversified",
  PFE: "Drug Manufacturers - General",
  ABBV: "Drug Manufacturers - General",
  MRK: "Drug Manufacturers - General",
  BMY: "Drug Manufacturers - General",
  LLY: "Drug Manufacturers - General",
  AMGN: "Drug Manufacturers - Specialty & Generic",
  GILD: "Drug Manufacturers - Specialty & Generic",
  REGN: "Biotechnology",
  VRTX: "Biotechnology",
  BIIB: "Drug Manufacturers - General",
  INCY: "Biotechnology",
  ILMN: "Diagnostics & Research",
  VTRS: "Drug Manufacturers - Specialty & Generic",
  OGN: "Drug Manufacturers - Specialty & Generic",
  // Healthcare - Services & Equipment
  UNH: "Healthcare Plans",
  ELV: "Healthcare Plans",
  CI: "Healthcare Plans",
  HCA: "Medical Care Facilities",
  HUM: "Healthcare Plans",
  CNC: "Healthcare Plans",
  MOH: "Healthcare Plans",
  TMO: "Diagnostics & Research",
  ABT: "Medical Devices",
  SYK: "Medical Devices",
  BDX: "Medical Devices",
  BSX: "Medical Devices",
  ISRG: "Medical Instruments & Supplies",
  EW: "Medical Devices",
  DXCM: "Medical Devices",
  MDT: "Medical Devices",
  IDXX: "Diagnostics & Research",
  A: "Diagnostics & Research",
  IQV: "Diagnostics & Research",
  MTD: "Diagnostics & Research",
  RMD: "Medical Devices",
  HOLX: "Medical Instruments & Supplies",
  ALGN: "Medical Devices",
  DGX: "Diagnostics & Research",
  LH: "Diagnostics & Research",
  BAX: "Medical Instruments & Supplies",
  DVA: "Medical Care Facilities",
  HSIC: "Medical Distribution",
  XRAY: "Medical Instruments & Supplies",
  TECH: "Diagnostics & Research",
  CTLT: "Drug Manufacturers - Specialty & Generic",
  ZTS: "Drug Manufacturers - Specialty & Generic",
  // Financials - Banks
  JPM: "Banks - Diversified",
  BAC: "Banks - Diversified",
  WFC: "Banks - Diversified",
  C: "Banks - Diversified",
  USB: "Banks - Regional",
  PNC: "Banks - Regional",
  TFC: "Banks - Regional",
  FITB: "Banks - Regional",
  HBAN: "Banks - Regional",
  CFG: "Banks - Regional",
  RF: "Banks - Regional",
  KEY: "Banks - Regional",
  MTB: "Banks - Regional",
  ZION: "Banks - Regional",
  // Financials - Investment & Services
  GS: "Capital Markets",
  MS: "Capital Markets",
  BLK: "Asset Management",
  SCHW: "Capital Markets",
  AXP: "Credit Services",
  COF: "Credit Services",
  CME: "Financial Data & Stock Exchanges",
  ICE: "Financial Data & Stock Exchanges",
  SPGI: "Financial Data & Stock Exchanges",
  MSCI: "Financial Data & Stock Exchanges",
  NDAQ: "Financial Data & Stock Exchanges",
  MKTX: "Capital Markets",
  CBOE: "Financial Data & Stock Exchanges",
  FDS: "Financial Data & Stock Exchanges",
  BK: "Asset Management",
  STT: "Asset Management",
  TROW: "Asset Management",
  NTRS: "Asset Management",
  RJF: "Capital Markets",
  IVZ: "Asset Management",
  BEN: "Asset Management",
  // Financials - Insurance
  CB: "Insurance - Property & Casualty",
  AON: "Insurance - Diversified",
  MMC: "Insurance - Diversified",
  AIG: "Insurance - Diversified",
  MET: "Insurance - Life",
  PRU: "Insurance - Life",
  AFL: "Insurance - Life",
  ALL: "Insurance - Property & Casualty",
  TRV: "Insurance - Property & Casualty",
  CINF: "Insurance - Property & Casualty",
  WRB: "Insurance - Specialty",
  LNC: "Insurance - Life",
  GL: "Insurance - Life",
  WTW: "Insurance - Diversified",
  // Consumer Staples
  PG: "Household & Personal Products",
  CL: "Household & Personal Products",
  KMB: "Household & Personal Products",
  CHD: "Household & Personal Products",
  CLX: "Household & Personal Products",
  EL: "Household & Personal Products",
  KO: "Beverages - Non-Alcoholic",
  PEP: "Beverages - Non-Alcoholic",
  MNST: "Beverages - Non-Alcoholic",
  KDP: "Beverages - Non-Alcoholic",
  STZ: "Beverages - Wineries & Distilleries",
  MDLZ: "Confectioners",
  HSY: "Confectioners",
  WMT: "Discount Stores",
  COST: "Discount Stores",
  TGT: "Discount Stores",
  DG: "Discount Stores",
  DLTR: "Discount Stores",
  KR: "Grocery Stores",
  SYY: "Food Distribution",
  ADM: "Farm Products",
  BG: "Farm Products",
  GIS: "Packaged Foods",
  K: "Packaged Foods",
  CAG: "Packaged Foods",
  SJM: "Packaged Foods",
  CPB: "Packaged Foods",
  TSN: "Packaged Foods",
  HRL: "Packaged Foods",
  MKC: "Packaged Foods",
  MO: "Tobacco",
  PM: "Tobacco",
  WBA: "Pharmaceutical Retailers",
  // Energy
  XOM: "Oil & Gas Integrated",
  CVX: "Oil & Gas Integrated",
  COP: "Oil & Gas E&P",
  SLB: "Oil & Gas Equipment & Services",
  EOG: "Oil & Gas E&P",
  MPC: "Oil & Gas Refining & Marketing",
  PSX: "Oil & Gas Refining & Marketing",
  VLO: "Oil & Gas Refining & Marketing",
  OXY: "Oil & Gas E&P",
  PXD: "Oil & Gas E&P",
  DVN: "Oil & Gas E&P",
  HES: "Oil & Gas E&P",
  HAL: "Oil & Gas Equipment & Services",
  FANG: "Oil & Gas E&P",
  BKR: "Oil & Gas Equipment & Services",
  TRGP: "Oil & Gas Midstream",
  WMB: "Oil & Gas Midstream",
  KMI: "Oil & Gas Midstream",
  OKE: "Oil & Gas Midstream",
  CTRA: "Oil & Gas E&P",
  // Industrials
  CAT: "Farm & Heavy Construction Machinery",
  HON: "Conglomerates",
  UPS: "Integrated Freight & Logistics",
  RTX: "Aerospace & Defense",
  MMM: "Conglomerates",
  GE: "Specialty Industrial Machinery",
  LMT: "Aerospace & Defense",
  BA: "Aerospace & Defense",
  NOC: "Aerospace & Defense",
  GD: "Aerospace & Defense",
  TDG: "Aerospace & Defense",
  HWM: "Aerospace & Defense",
  DE: "Farm & Heavy Construction Machinery",
  UNP: "Railroads",
  CSX: "Railroads",
  NSC: "Railroads",
  FDX: "Integrated Freight & Logistics",
  DAL: "Airlines",
  UAL: "Airlines",
  LUV: "Airlines",
  WM: "Waste Management",
  RSG: "Waste Management",
  EMR: "Specialty Industrial Machinery",
  ITW: "Specialty Industrial Machinery",
  ETN: "Specialty Industrial Machinery",
  ROK: "Specialty Industrial Machinery",
  PH: "Specialty Industrial Machinery",
  DOV: "Specialty Industrial Machinery",
  AME: "Specialty Industrial Machinery",
  IR: "Specialty Industrial Machinery",
  GNRC: "Specialty Industrial Machinery",
  NDSN: "Specialty Industrial Machinery",
  HUBB: "Electrical Equipment & Parts",
  PCAR: "Farm & Heavy Construction Machinery",
  CTAS: "Specialty Business Services",
  FAST: "Industrial Distribution",
  PAYX: "Staffing & Employment Services",
  VRSK: "Consulting Services",
  SWK: "Tools & Accessories",
  OTIS: "Specialty Industrial Machinery",
  CARR: "Building Products & Equipment",
  XYL: "Specialty Industrial Machinery",
  WAB: "Railroads",
  J: "Engineering & Construction",
  PWR: "Engineering & Construction",
  AOS: "Specialty Industrial Machinery",
  ALLE: "Security & Protection Services",
  // Utilities
  NEE: "Utilities - Regulated Electric",
  DUK: "Utilities - Regulated Electric",
  SO: "Utilities - Regulated Electric",
  D: "Utilities - Regulated Electric",
  AEP: "Utilities - Regulated Electric",
  SRE: "Utilities - Diversified",
  EXC: "Utilities - Regulated Electric",
  XEL: "Utilities - Regulated Electric",
  ED: "Utilities - Regulated Electric",
  WEC: "Utilities - Regulated Electric",
  ES: "Utilities - Regulated Electric",
  AWK: "Utilities - Regulated Water",
  AEE: "Utilities - Regulated Electric",
  DTE: "Utilities - Regulated Electric",
  CMS: "Utilities - Regulated Electric",
  FE: "Utilities - Regulated Electric",
  PPL: "Utilities - Regulated Electric",
  EVRG: "Utilities - Regulated Electric",
  ATO: "Utilities - Regulated Gas",
  NI: "Utilities - Regulated Gas",
  PNW: "Utilities - Regulated Electric",
  LNT: "Utilities - Regulated Electric",
  // Real Estate
  AMT: "REIT - Specialty",
  PLD: "REIT - Industrial",
  CCI: "REIT - Specialty",
  EQIX: "REIT - Specialty",
  PSA: "REIT - Specialty",
  SPG: "REIT - Retail",
  O: "REIT - Retail",
  DLR: "REIT - Specialty",
  WELL: "REIT - Healthcare Facilities",
  AVB: "REIT - Residential",
  EQR: "REIT - Residential",
  VTR: "REIT - Healthcare Facilities",
  ARE: "REIT - Office",
  MAA: "REIT - Residential",
  UDR: "REIT - Residential",
  ESS: "REIT - Residential",
  PEAK: "REIT - Healthcare Facilities",
  HST: "REIT - Hotel & Motel",
  KIM: "REIT - Retail",
  REG: "REIT - Retail",
  CPT: "REIT - Residential",
  BXP: "REIT - Office",
  SLG: "REIT - Office",
  FRT: "REIT - Retail",
  IRM: "REIT - Specialty",
  // Communication Services
  DIS: "Entertainment",
  CMCSA: "Telecom Services",
  VZ: "Telecom Services",
  T: "Telecom Services",
  TMUS: "Telecom Services",
  CHTR: "Telecom Services",
  NFLX: "Entertainment",
  EA: "Electronic Gaming & Multimedia",
  ATVI: "Electronic Gaming & Multimedia",
  TTWO: "Electronic Gaming & Multimedia",
  WBD: "Entertainment",
  PARA: "Entertainment",
  FOX: "Broadcasting",
  FOXA: "Broadcasting",
  NWS: "Publishing",
  NWSA: "Publishing",
  OMC: "Advertising Agencies",
  IPG: "Advertising Agencies",
  MTCH: "Internet Content & Information",
  LYV: "Entertainment",
  // Materials
  LIN: "Specialty Chemicals",
  APD: "Specialty Chemicals",
  SHW: "Specialty Chemicals",
  ECL: "Specialty Chemicals",
  PPG: "Specialty Chemicals",
  IFF: "Specialty Chemicals",
  DD: "Specialty Chemicals",
  EMN: "Specialty Chemicals",
  ALB: "Specialty Chemicals",
  CE: "Specialty Chemicals",
  FMC: "Agricultural Inputs",
  CF: "Agricultural Inputs",
  MOS: "Agricultural Inputs",
  NEM: "Gold",
  FCX: "Copper",
  NUE: "Steel",
  VMC: "Building Materials",
  MLM: "Building Materials",
  BALL: "Packaging & Containers",
  AMCR: "Packaging & Containers",
  IP: "Packaging & Containers",
  WRK: "Packaging & Containers",
  SEE: "Packaging & Containers",
  PKG: "Packaging & Containers",
  AVY: "Packaging & Containers",
  // Consumer Discretionary
  AMZN: "Internet Retail",
  TSLA: "Auto Manufacturers",
  HD: "Home Improvement Retail",
  MCD: "Restaurants",
  NKE: "Footwear & Accessories",
  SBUX: "Restaurants",
  LOW: "Home Improvement Retail",
  TJX: "Apparel Retail",
  BKNG: "Travel Services",
  CMG: "Restaurants",
  ORLY: "Specialty Retail",
  AZO: "Specialty Retail",
  ROST: "Apparel Retail",
  DHI: "Residential Construction",
  LEN: "Residential Construction",
  PHM: "Residential Construction",
  NVR: "Residential Construction",
  BBY: "Specialty Retail",
  EBAY: "Internet Retail",
  ETSY: "Internet Retail",
  MAR: "Lodging",
  HLT: "Lodging",
  GRMN: "Scientific & Technical Instruments",
  POOL: "Industrial Distribution",
  RCL: "Travel Services",
  CCL: "Travel Services",
  WYNN: "Resorts & Casinos",
  LVS: "Resorts & Casinos",
  MGM: "Resorts & Casinos",
  DRI: "Restaurants",
  YUM: "Restaurants",
  DPZ: "Restaurants",
  DKNG: "Gambling",
  APTV: "Auto Parts",
  F: "Auto Manufacturers",
  GM: "Auto Manufacturers",
  KMX: "Auto & Truck Dealerships",
  GPC: "Specialty Retail",
  LKQ: "Auto Parts",
  ULTA: "Specialty Retail",
  LULU: "Apparel Manufacturing",
  TPR: "Luxury Goods",
  RL: "Apparel Manufacturing",
  VFC: "Apparel Manufacturing",
  HAS: "Leisure",
  BWA: "Auto Parts",
  // Information Services & Payments
  V: "Credit Services",
  MA: "Credit Services",
  PYPL: "Credit Services",
  FIS: "Information Technology Services",
  FISV: "Information Technology Services",
  ADP: "Staffing & Employment Services",
  GPN: "Information Technology Services",
  BR: "Information Technology Services",
  JKHY: "Information Technology Services",
  CPAY: "Information Technology Services",
};
